version: "3.7"

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mystudies
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db-mysql:/var/lib/mysql
    networks:
      - examplenetwork
networks:
  examplenetwork:
    driver: bridge

volumes:
  db-mysql:
